source 'https://github.com/componentizationdemo/PXModulSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'PXPersonInfoKit_Example' do
  pod 'PXPersonInfoKit', :path => '../'

  target 'PXPersonInfoKit_Tests' do
    inherit! :search_paths

    
  end
end
